### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by Rugleh** [tylermercer/nuxt-netlifycms-boilerplate#10]
Hi @tylermercer 

Your repo is just what I was looking for!

After deploying the site in Netlify im getting a Page not found error

> Page Not Found
> Looks like you've followed a broken link or entered a URL that doesn't exist on this site.

Sorry to open an issue about this, maybe I'm doing something wrong

Thank you in advance!

**Comment by tylermercer** [comment]
Yeah, I encountered that yesterday. You have to go to Deploys > Deploy Settings and set the build command to `npm run generate` and the publish directory to `dist`. Then redo the deploy.

Hopefully today I'll be able to find a way to have those values set automatically when you click the "Deploy to Netlify" button. Until I figure that out, I'll leave this issue open.

Thanks for reporting the issue!

**Comment by tylermercer** [comment]
Fixed in [2f4114f6](https://github.com/tylermercer/nuxt-netlifycms-boilerplate/commit/2f4114f62e889eed933302d1e9733ceecd1cfcd1). Happy coding! 🙂

**Comment by Rugleh** [comment]
Oh, I see what I was missing

Thank you!
