### ISSUE TITLE
Login error?

### ISSUE THREAD

**Issue by wimmar** [tylermercer/nuxt-netlifycms-boilerplate#11]
Hi,

How can you log in on the admin page?
\+ When entering random login data, the following error occurs: 

`Invariant Violation: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=t%3A%20invalid_grant%3A%20No%20user%20found%20with%20this%20email&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. `

Kind regards

**Comment by tylermercer** [comment]
Hi @wimmar,

Please report this bug [here](https://github.com/netlify/netlify-cms/issues/new?template=bug_report.md). It's a bug in NetlifyCMS, not in my boilerplate.

As far as how to log in, you have to send yourself an invitation from your Netlify dashboard after configuring Netlify Identity. Please see the Netlify documentation for more information on this.

Also, I'm not sure if you're trying to log in to my example website or your own instance of it. You won't be able to log in to mine; I have not made the admin settings publicly accessible. If you are trying to log in to mine, please go [here](https://app.netlify.com/start/deploy?repository=https://github.com/tylermercer/nuxt-netlifycms-boilerplate) to create your own instance on Netlify, and log in to that instead. (As mentioned above, you'll need to configure Netlify Identity for this to work.)

I hope this helps! Thanks for reporting the issue!
