### ISSUE TITLE
Can't update page/blog

### ISSUE THREAD

**Issue by mugas** [tylermercer/nuxt-netlifycms-boilerplate#12]
Hi, 

Thank you for your repo. It is perfect. 
But I am trying to create new post or edit the ones there, the same for the pages and gives me a error : "Failed to persist entry: API_ERROR: Operator microservice headers missing". And the pages no error but can't see them.
I search the error, I found something somehow almost similar that was related to Netlify CMS but I didn't had the same specifications so...
Did you had that error somewhere?
Before your repo I tried other other and the blog and pages were working fine, so I am not getting it.
Thank you

**Comment by mugas** [comment]
Ok, it works now. Didn't do nothing besides went to be and try again:) Thanks

**Comment by tylermercer** [comment]
@mugas,

Glad it started working! Let me know if you run into any more problems with it and I'll see what I can do.
